laguage: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_2434caf31dfd_key -iv $encrypted_2434caf31dfd_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
